version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: recettage_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recettage
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - recettage_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: recettage_phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    ports:
      - "8081:80"
    networks:
      - recettage_network

networks:
  recettage_network:
    driver: bridge

volumes:
  db_data:
